# Generated by Django 4.2 on 2023-04-12 22:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Місце посадки')),
            ],
            options={
                'verbose_name': 'Місце посадки',
                'verbose_name_plural': 'Місця посадки',
            },
        ),
        migrations.CreateModel(
            name='TourObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('photo', models.FileField(upload_to='tour_objects_photo/', verbose_name='Фото')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': "Екскурсійний об'єкт",
                'verbose_name_plural': "Екскурсійні об'єкти",
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва туру')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Короткий опис туру')),
                ('main_photo', models.FileField(blank=True, upload_to='tour_main_photo/', verbose_name='Головне фото')),
                ('plan', ckeditor.fields.RichTextField(blank=True, verbose_name='План туру')),
                ('price_include', ckeditor.fields.RichTextField(blank=True, verbose_name='У вартість туру входить')),
                ('price_exclude', ckeditor.fields.RichTextField(blank=True, verbose_name='У вартість туру не входить')),
                ('food', ckeditor.fields.RichTextField(blank=True, verbose_name='Харчування')),
                ('ticket', ckeditor.fields.RichTextField(blank=True, verbose_name='Вхідні квитки')),
                ('notes', ckeditor.fields.RichTextField(blank=True, verbose_name='Додаткова інформація')),
                ('url', models.SlugField(blank=True, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_place', models.ManyToManyField(blank=True, to='main.startplace', verbose_name='Місце посадки')),
                ('tour_objects', models.ManyToManyField(to='main.tourobject', verbose_name="Екскурсійні об'єкти")),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Тури',
            },
        ),
    ]
