# Generated by Django 4.2 on 2023-04-13 17:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tour_tour_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourobject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tourobject',
            name='photo',
            field=models.FileField(blank=True, upload_to='tour_objects_photo/', verbose_name='Фото'),
        ),
    ]
