# Generated by Django 4.2 on 2023-04-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_priceexclude_priceinclude_remove_tour_price_exclude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceexclude',
            options={'verbose_name': 'Тур вкючає', 'verbose_name_plural': 'Тур не включає '},
        ),
    ]
