# Generated by Django 4.2 on 2023-04-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_priceexclude_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceexclude',
            options={'verbose_name': 'Тур не вкючає', 'verbose_name_plural': 'Тур не вкючає'},
        ),
        migrations.AlterModelOptions(
            name='priceinclude',
            options={'verbose_name': 'Тур вкючає', 'verbose_name_plural': 'Тур вкючає'},
        ),
    ]
