# Generated by Django 4.2 on 2023-05-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tour_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=60, null=True, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=9, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.tour')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
