# Generated by Django 4.2 on 2023-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Додаткова інформація'),
        ),
    ]
