# Generated by Django 4.2 on 2023-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-id'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Тури'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва туру'),
        ),
    ]
