# Generated by Django 4.2 on 2023-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_tour_options_alter_tour_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="url",
        ),
    ]
